name: Linux builds (basic2)

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.compiler.cxx}}, C++${{matrix.std}}, ${{matrix.build_type}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - {cxx: clang++, other_pkgs: clang}
        build_type: [Debug, Release]
        std: [11, 14, 17, 20]
        #std: [11, 14, 17, 20]
        #exclude:
        #  - compiler.cxx: "g++-{5,6,7,8,9,10}"
        #    std: 17
        #  - compiler.cxx: "g++-{5,6,7,8,9,10}"
        #    std: 20
        #  - compiler.cxx: "clang++-{6.0,7,8,9,10}"
        #    std: 17
        #  - compiler.cxx: "clang++-{6.0,7,8,9,10}"
        #    std: 20

    steps:
    - uses: actions/checkout@v4

    #- name: Prepare environment
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install -y ninja-build ${{matrix.compiler.other_pkgs}}

    #- name: Configure CMake
    #  env:
    #    CXX: ${{matrix.compiler.cxx}}
    #  run: |
    #    cmake -B build \
    #          -DCMAKE_BUILD_TYPE=${{matrix.built_type}} \
    #          -DCMAKE_CXX_STANDARD=${{matrix.std}} \
    #          -DCMAKE_CXX_STANDARD_REQUIRED=ON \
    #          -DCMAKE_CXX_EXTENSIONS=OFF \
    #          -DRAPIDFUZZ_BUILD_TESTING=1 \
    #          -DRAPIDFUZZ_ENABLE_LINTERS=1 \
    #          -DRAPIDFUZZ_BUILD_FUZZERS=1 \
    #          -G Ninja

    - name: Configure CMake
      run: |
        cmake -B build \
              -DCMAKE_BUILD_TYPE=${{matrix.built_type}} \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DRAPIDFUZZ_BUILD_TESTING=1 \
              -DRAPIDFUZZ_ENABLE_LINTERS=1 \
              -DRAPIDFUZZ_BUILD_FUZZERS=1

    #- name: Build
    #  working-directory: build
    #  run: ninja

    - name: Build
      run: cmake --build build --config ${{matrix.built_type}}

    - name: Test
      working-directory: build
      run: ctest -C ${{matrix.built_type}} --rerun-failed --output-on-failure

    - name: Fuzz Test
      working-directory: build
      run: |
          fuzzing/fuzz_lcs_similarity -max_total_time=30
          fuzzing/fuzz_levenshtein_distance -max_total_time=30
          fuzzing/fuzz_levenshtein_editops -max_total_time=30
          fuzzing/fuzz_indel_distance -max_total_time=30
          fuzzing/fuzz_indel_editops -max_total_time=30
          fuzzing/fuzz_osa_distance -max_total_time=30
          fuzzing/fuzz_damerau_levenshtein_distance -max_total_time=30"""

