name: Linux builds (basic)

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.cxx}}, C++${{matrix.std}}, ${{matrix.build_type}}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-5
          - g++-6
          - g++-7
          - g++-8
          - g++-9
          - g++-10
          - clang++-6.0
          - clang++-7
          - clang++-8
          - clang++-9
          - clang++-10
        build_type: [Debug, Release]
        std: [11]
        include:
          - cxx: g++-5
            other_pkgs: g++-5
          - cxx: g++-6
            other_pkgs: g++-6
          - cxx: g++-7
            other_pkgs: g++-7
          - cxx: g++-8
            other_pkgs: g++-8
          - cxx: g++-9
            other_pkgs: g++-9
          - cxx: g++-10
            other_pkgs: g++-10
          - cxx: clang++-6.0
            other_pkgs: clang-6.0
          - cxx: clang++-7
            other_pkgs: clang-7
          - cxx: clang++-8
            other_pkgs: clang-8
          - cxx: clang++-9
            other_pkgs: clang-9
          - cxx: clang++-10
            other_pkgs: clang-10

          - cxx: clang++-10
            other_pkgs: clang-10
            std: 14
            build_type: Debug
          - cxx: clang++-10
            other_pkgs: clang-10
            std: 17
            build_type: Debug
          - cxx: clang++-10
            other_pkgs: clang-10
            std: 20
            build_type: Debug
          - cxx: g++-10
            other_pkgs: g++-10
            std: 14
            build_type: Debug
          - cxx: g++-10
            other_pkgs: g++-10
            std: 17
            build_type: Debug
          - cxx: g++-10
            other_pkgs: g++-10
            std: 20
            build_type: Debug

          - cxx: clang++-10
            other_pkgs: clang-10
            std: 14
            build_type: Release
          - cxx: clang++-10
            other_pkgs: clang-10
            std: 17
            build_type: Release
          - cxx: clang++-10
            other_pkgs: clang-10
            std: 20
            build_type: Release
          - cxx: g++-10
            other_pkgs: g++-10
            std: 14
            build_type: Release
          - cxx: g++-10
            other_pkgs: g++-10
            std: 17
            build_type: Release
          - cxx: g++-10
            other_pkgs: g++-10
            std: 20
            build_type: Release

    steps:
    - uses: actions/checkout@v4

    - name: Add repositories for older GCC
      run: |
        sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ bionic main'
        sudo apt-add-repository 'deb http://azure.archive.ubuntu.com/ubuntu/ bionic universe'
      if: ${{ matrix.cxx == 'g++-5' || matrix.cxx == 'g++-6' }}

    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build ${{matrix.other_pkgs}}

    - name: Configure CMake
      env:
        CXX: ${{matrix.cxx}}
      run: |
        cmake -B build \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -DCMAKE_CXX_STANDARD_REQUIRED=ON \
              -DCMAKE_CXX_EXTENSIONS=OFF \
              -DRAPIDFUZZ_BUILD_TESTING=1 \
              -DRAPIDFUZZ_ENABLE_LINTERS=1 \
              -G Ninja

    - name: Build
      working-directory: build
      run: ninja

    - name: Test
      working-directory: build
      run: ctest -C ${{matrix.build_type}} --rerun-failed --output-on-failure -j `nproc`

