name: Linux builds (basic)

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.compiler}}, C++${{matrix.std}}, ${{matrix.build_type}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-13
          - clang-18
        build_type: [Debug, Release]
        std: [11, 14, 17, 20]

    steps:
    - uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build ${{matrix.other_pkgs}}

    - name: Configure CMake
      env:
        CXX: ${{matrix.cxx}}
      run: |
        cmake -B build \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              -DCMAKE_CXX_STANDARD_REQUIRED=ON \
              -DCMAKE_CXX_EXTENSIONS=OFF \
              -DRAPIDFUZZ_BUILD_TESTING=1 \
              -DRAPIDFUZZ_ENABLE_LINTERS=1 \
              -G Ninja

    - name: Build
      working-directory: build
      run: ninja

    - name: Test
      working-directory: build
      run: ctest -C ${{matrix.build_type}} --rerun-failed --output-on-failure -j `nproc`

